meson.build: Fix include path for numpy [YOCIMX-8735]
On walnascar, a numpy include path change causes a build break:

Check usable header "numpy/arrayobject.h" with dependency python3-embed:
NO
../git/meson.build:574: WARNING: Found python3, but failed to find
numpy.
../git/meson.build:575: WARNING: Disable nnstreamer-python3.
../git/meson.build:581:4: ERROR: Problem encountered: Cannot find
python3 with numpy support
ERROR: meson failed

Upstream-Status: Pending
Signed-off-by: Neena Busireddy <neenareddy.busireddy@nxp.com>
Signed-off-by: Nicolas Goueslain <nicolas.goueslain@nxp.com>